### PR TITLE
Update model_import.py

### PR DESCRIPTION
**Pull request by altophohe**
Hello. I often encountered an Attribute Error when loading my YAML file and I tried to slightly modify the code to have it show an error message when the error pops up due to an attribute error. 

In particular, I move the loading file part forward before " if check:~~~" part runs. In this case, you would see the error message if you made a syntax error in writing your YAML file. 

I am not sure this way of revision would be proper. Any suggestion from experienced users would be more than welcome. Thanks.

### CODE REVIEW

**Comment by albop** [comment]
Thank you @altophohe . This should work, but I'm a bit surprised you had to move the linter since there is there seems to be a bit of code here https://github.com/EconForge/dolo/blob/master/dolo/linter.py (430-435), which does the same.
Actually, the best way to proceed would probably to:
- in `model_import.py` import the file surrounded by try/except like you do
- in `lint.py`, fix the lint function so that it can either take a string, in which case it parses it as it currently does or, optionnally a yaml structure 
- in `model_import.py` pass the parsed structure to lint so that the model text is parsed only once

Does it make sense to you? Any chance you can fix the pull request accordingly?

**Comment by altophohe** [comment]
Hmm. I moved the try/except part before the linter since I found that the yaml syntax error cannot be caught otherwise, but an error pops up during linter. Since linter does not indicates the syntax error(as far as I know), then an user may get lost and cannot see what was her real problem.  If we move the try/except part forward, then the program barf the error message when it detects any syntax error during parsing YAML file. 

I will try to follow your instruction for further improvement. thanks for advice.

**Comment by altophohe** [comment]
And I have another question. My try/except part catches an attribute error due to a mistake in writing a yaml file. In contrast, the similar part in linter catches Exceptions when loading yaml file. Do those two try/except parts play the exactly same role and catch the same error(same case)? If not, I am afraid that the linter may not work properly if I get rid of the similar part in linter.  How do you think?

**Comment by albop** [comment]
Well, the first order thing is to tell user he got an user that is due to
the yaml syntax, not anything to do with the model. So I'm good with
catching any exception here. Plus when you raise this exception it
ultimately provides information about what happened.
BTW, the way you currently print the exception before running the command
again is not useful. You can print the message if you want then raise the
exception directly (`raise exc`). No need to run the command again.

**Pull request merged**
