### PR TITLE
Model classification

### PR DESCRIPTION
**Pull request by yaniv256**
Let me suggest the way I was thinking of these things. I think the ideas are pretty similar so for now it is more a matter of notation (at least if I understand correctly).

I'll be going over the classification doc slowly, suggesting modifications in small bits and awaiting discussion to proceed. For this first commit I tweaked the formulation of the value function and generalized value function.

### CODE REVIEW

**Comment by yaniv256** [comment]
I refined my suggestion a bit.

**Comment by yaniv256** [comment]
Do you have a need for U^* that is not a dot product? Are there gains from making dot product U*s a class of models?

**Comment by yaniv256** [comment]
[Tourchpad](https://torchpad.com/workspace/wikis/yaniv256/pages/Model+classification) is also an option. Very close to markdown, and you can login with GitHub.

**Comment by yaniv256** [comment]
I think I am going to close this PR. We can discuss it on the [test wiki](http://yaniv-benami.com/mediawiki/index.php/Main_Page), but I'll want to think about it first. Do you mind if I post the Model Classification stuff on the test wiki?

**Comment by yaniv256** [comment]
Actually, since it's your creation it's better if you log in the wiki and post it there yourself. That way the edit record will reflect the contribution.

**Comment by albop** [comment]
I created an account, but haven't copied the edits you made in the notebook.
Since that wiki is experimental, I suggest that we use it to edit the text and make the equations square. When ready I'll copy it back to the dolo doc or the dolo wiki where it belongs (to replace this old one https://github.com/EconForge/dolo/wiki/Model-specification ).
The wiki question will come back again and again, so we'll need a permanent solution at some point. It is unfortunate, that they all seem to involve having a dedicated server.

**Comment by yaniv256** [comment]
That is great. I'm closing.

**Comment by albop** [comment]
Just pinging @npalmer on this one.
There is one option I haven't given much thought yet but which should work in theory: it would consist in regenerating a static version of the wiki served at dolo.github.io everytime a commit is made to the wiki.

**Pull request closed without merging**
